language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: RL5P/r2OT4Sz3fZiHyLpLSWJFZzigoQYTkfLcSZ7WEnspuCay1zQRZO92Qv5ON5DvuwfB2KXgR1goE8xJaWSCyuxRuWNYHq13BGfeCouwa8XFsWiGjngWneT3P8bT7NsBq6IyOt/no0ozs/jrXuIHN/XbH5OyY1XjpOEDBZH7bfM3c9qVDEJjWdYXOQDAZbW1d/1AJU6rH/6S8BD9g3Ab8mj7I1fm8Uh+PPRSJMUPo8YshUpg8QpuxIkXbOoYZW/OzdmGEeTJUjhti1l2IGUXyUoA5i15jNvcbXilUE+28sC5iPZSBeLPWSiO9jwdn18r9QUj3qSSWJl1sHdDM+Eiw2OTteMG/cIwGCyaQuntJFX9CPwSRgygn2C5XYTtMPw4uTvdX6JKSENJdlWm8qlIljBikkTf0yoV3OHwPE59vDbruLS9BxGjrv8a+HTk8xXuOOdsQ+6TwK67I476iIDEU/0tPJATE1whA7dAkSvTRXlG+2J/UqXiIZtv35v//R9mQC/ttAKOzbaAR8NneRcTU21+2OzIY+ATWVcsaKhVNOVgD/bfxrZej3Toiypy12CvZOreP4TIkvLdWke32N4GxradfX0IVio6lmZReVnT2FgXpQq02Uv05bdfU2T8LAk+M6TOMNBKeWgJkYi1DFImVgZ1dGr1xbBZA9uZCpOM/c=
  app: battle-skratch-server
  on:
    repo: IamGrimUs/battle-skratch-server
